services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: ["14330:1433"]
    env_file:
      - .env.dev
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data

  runner:
    user: root
    build:
      context: .
      dockerfile: RunnerApp/Dockerfile
    environment:
      HOST_JOBS_DIR: ${PWD}/jobs
    volumes:
      - ./jobs:/app/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  cpp-runner-image:
    build:
      context: ./JudgeAPI.API/CppRunnerImage
    image: judge-cpp-runner
    volumes:
      - ./jobs:/app/jobs

volumes:
  sqlvolume:
  redisdata:
